services:
  mysql-db:
    image: mysql:8.0
    container_name: bank-cards-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bank_rest_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d

    networks:
      - bank-cards-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  bank-cards-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-cards-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bank_rest_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_LIQUIBASE_ENABLED: false
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - bank-cards-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  bank-cards-network:
    driver: bridge