server:
  port:
    8080

spring:
  config:
    import: env.properties

  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  liquibase:
    change-log: classpath:db/migration/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

app:
  security:
    jwt:
      secret-key: ${jwt.secret}
      expiration-time: ${jwt.lifetime}
      refresh-token:
        expiration-time: 604800000
logging:
  level:
    com.example.bankcards.exception.GlobalExceptionHandler: DEBUG
    com.example.bankcards.service: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
